FROM amazoncorretto:11-alpine as builder
WORKDIR /usr/src/myapp
COPY . /usr/src/myapp
RUN ./gradlew clean bootJar

FROM amazoncorretto:11-alpine
WORKDIR /usr/src/myapp
COPY --from=builder /usr/src/myapp/build/libs/*.jar /usr/src/myapp
ENTRYPOINT java -jar /usr/src/myapp/*.jar