FROM openjdk:11-jdk-slim as builder
WORKDIR /usr/src/myapp
COPY . /usr/src/myapp
RUN ./gradlew clean bootJar

FROM openjdk:11-jre-slim
WORKDIR /usr/src/myapp
COPY --from=builder /usr/src/myapp/build/libs/*.jar /usr/src/myapp
ENTRYPOINT java -jar /usr/src/myapp/*.jar