spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
  endpoint:
    metrics:
      enabled: true